
Var
// area, latas, volume em litros e final
a, l , v , f:real

Inicio
// Inserindo a área desejada e já tendo os valores em litros e de custo
//pré determinados, é feito o cálculo de latas necessárias e o custo.
escreval("Informe a área em m2: ")
leia(a)

l <- a / 5
v <- l * 10
f <- l * 120

escreval(" A quantidade de latas necessárias será:", l, " e o valor será:", f)



Fimalgoritmo
