

Var
//Area, basemaior, base menor e altura.
A, bmaior, bmenor, H :Real

Inicio
// Calcula-se a área inserindo os valores das variávies e realizando o cálculo
// na variável A.
escreval("Digite a base maior:")
leia(bmaior)
escreval("Digite a base menor:")
leia(bmenor)
escreval("Digite a altura:")
leia(H)
A<- (((bmaior + bmenor)) * H) / 2)
escreval("A área do trapézio será = ",A)

Fimalgoritmo
