
//Atividade: Lista de Exercícios 1 - Exercício 9
Algoritmo "ex9"

Var
//kilometros, dias e total
km, d, t: REAL

Inicio
//calcula o total a pagar em um aluguel de um carro
// de acordo com a distância percorrida e os dias


escreval ("Informe a quantidade de Km percorridos: ")
leia (km)
escreval ("Informe a quantidade de dias: ")
leia (d)
t <- 0.50 * km + 90 * d
escreval ("Total a pagar: R$", t)


Fimalgoritmo
