
//Atividade: Lista de Exercícios 1 - Exercício 1

Algoritmo "ex1"
//nota1 é a primeira nota e nota2 é a segunda nota
Var

nota1, nota2, media: REAL

Inicio
//calculo da média entre as duas notas
escreval ("Digite a primeira nota: ")
leia (nota1)
escreval ("Digite a segunda nota: ")
leia (nota2)
media <- (nota1 + nota2) / 2
escreval ("O resultado da média entre", nota1, " e", nota2, " é:", media)


Fimalgoritmo
