Algoritmo "LISTA 2 - EXERCICIO 3"
//ATIVIDADE AVALIATIVA - ALGORITMOS E ESTRUTURA DE DADOS
//Nome: Leonardo Henrique Benatti e Souza
//RA: 5159286
//Atividade: Lista de Exercícios 2 - Exercício 3

Var
//metros por segundo e conversão para KM/h
metros, km: REAL

Inicio
//É inserido o valor em m/s e depois convertido para km/h.
escreval("Informe a velocidade em m/s:")
leia(metros)
km <- metros *3.6
escreval("O valor em Km/h será:",km)

Fimalgoritmo