
//Atividade: Lista de Exercícios 1 - Exercício 7
Algoritmo "ex7"

Var
//metros, kilometros, centimetros
m, km, cm: REAL

Inicio
//Conversor de unidades de medida
escreval ("Digite uma distância em metros: ")
leia (m)
km <- m / 1000
cm <- m * 100
escreval ("A distância de", m, "m corresponde a:", km, "km")
escreval ("A distância de", m, "m corresponde a:", cm, "cm")

Fimalgoritmo
