
//Atividade: Lista de Exercícios 1 - Exercício 6
Algoritmo "ex6"

Var
//custo, preço e valor final
c, p, v: REAL

Inicio
//calcula quantos ingressos devem ser vendidos
//de acordo com o custo total do espetáculo

escreval("Informe o custo do espetáculo teatral: ")
leia (c)
escreval ("Informe o preço do convite do espetáculo: ")
leia(p)
v <- c / p
escreval ("Devem ser vendidos pelo menos", v, " convites")


Fimalgoritmo
