Algoritmo "LISTA 2 - EXERCICIO 2"
//ATIVIDADE AVALIATIVA - ALGORITMOS E ESTRUTURA DE DADOS
//Nome: Leonardo Henrique Benatti e Souza
//RA: 5159286
//Atividade: Lista de Exercícios 2 - Exercício 2


Var
//Polegadas e calculo.
p, c : REAL


Inicio
//Informado o tamanho em polegadas
//é feito uma conversão para Cm através do cálculo.
escreval("Digite a medida em polegadas:")
leia(p)

c <- P * 2.54

escreval("A medida em centímetros será:",c)


Fimalgoritmo