Algoritmo "LISTA 2 - EXERCICIO 4"
//ATIVIDADE AVALIATIVA - ALGORITMOS E ESTRUTURA DE DADOS
//Nome: Leonardo Henrique Benatti e Souza
//RA: 5159286
//Atividade: Lista de Exercícios 2 - Exercício 4


Var
// graus kelvin e conversão
k, c : REAL

Inicio
//Inserir o valor em graus KELVIN e a conversão será feita para graus CELCIUS
escreval("Informe o valor em graus Kelvin:")
leia(k)
c <- k - 273.15
escreval("O valor em graus Celcius será:",C)

Fimalgoritmo